class Config:
    metaPath = "./sample_wts/sample.meta"
    pbPath = "./sample_wts/sample.pb"
    export_path = "./export"
    yolo_config = "yolov2-tiny.cfg"
    yolo_wts = "./sample_wts/yolov2-tiny.weights"
    input_size = [416, 416]
    signature_name = "predict"
    model_platform = "tensorflow"
    input_name = "input"
    output_name = "output"
    name = "yolov2"
    TF_SERVING_HOSTNAME = "localhost"
    TENSORFLOW_SERVING_PORT = 9000
    labels = {"labels": ['person',
                         'bicycle',
                         'car',
                         'motorbike',
                         'aeroplane',
                         'bus',
                         'train',
                         'truck',
                         'boat',
                         'traffic light',
                         'fire hydrant',
                         'stop sign',
                         'parking meter',
                         'bench',
                         'bird',
                         'cat',
                         'dog',
                         'horse',
                         'sheep',
                         'cow',
                         'elephant',
                         'bear',
                         'zebra',
                         'giraffe',
                         'backpack',
                         'umbrella',
                         'handbag',
                         'tie',
                         'suitcase',
                         'frisbee',
                         'skis',
                         'snowboard',
                         'sports ball',
                         'kite',
                         'baseball bat',
                         'baseball glove',
                         'skateboard',
                         'surfboard',
                         'tennis racket',
                         'bottle',
                         'wine glass',
                         'cup',
                         'fork',
                         'knife',
                         'spoon',
                         'bowl',
                         'banana',
                         'apple',
                         'sandwich',
                         'orange',
                         'broccoli',
                         'carrot',
                         'hot dog',
                         'pizza',
                         'donut',
                         'cake',
                         'chair',
                         'sofa',
                         'pottedplant',
                         'bed',
                         'diningtable',
                         'toilet',
                         'tvmonitor',
                         'laptop',
                         'mouse',
                         'remote',
                         'keyboard',
                         'cell phone',
                         'microwave',
                         'oven',
                         'toaster',
                         'sink',
                         'refrigerator',
                         'book',
                         'clock',
                         'vase',
                         'scissors',
                         'teddy bear',
                         'hair drier',
                         'toothbrush']}
